wayne:
  host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${wayne.host}:8761/eureka

spring:
  # 默认数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${wayne.host}:3306/card?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # spring cache
  cache:
    cache-names: c1,diff
  # redis
  redis:
    timeout: 60000ms   # 连接超时时间（毫秒）
    database: 0        # 数据库索引（默认为0）
    password:          # 密码，若没有，不填写
    cluster:
      nodes: #集群ip+端口号
        - ${wayne.host}:6379
#        - 127.0.0.1:7032
#      max-redirects: 3
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5      # 连接池中的最大空闲连接
        min-idle: 2      # 连接池中的最小空闲连接
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）






