server:
  port: 8762

spring:
  application:
    name: eureka-b

eureka:
  instance:
    hostname: eureka-b  # 作为eureka-a 注册获取地址
  client:
    # 都为true互相注册
    registerWithEureka:  true
    # 拉取注册表 同步eureka使用 单机为false
    fetchRegistry: true
    # 注册到eureka-a上
    serviceUrl:
      defaultZone: http://eureka-a:8761/eureka
