# 集成hystrix 比zuul多了限流 ,请求类型限制
# 路径重写 动态路由
wayne:
  host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${wayne.host}:8761/eureka

spring:
  cloud:
    gateway:
      # 配置路由转发
      routes:
        - id: test # 唯一id即可
          uri: http://www.baidu.com #转发的地址
          filters: # 局部过滤(只在本route生效) (default-filters全局过滤)
            - AddRequestParameter=name,wayne  # 过滤器 请求转发时添加参数 https://www.baidu.com/?name=wayne
          predicates:
            - Path=/test #符合规则跳转 即localhost:8080/test
    #            - Method=GET # 只转发GET请求 POST请求导致404,没代理转发过去
    #            - Query=name # 请求必须携带name参数 否则不转发 404
    #            - Query=name,java.* # 请求必须携带name参数,且值必须是java开始否则不转发 404
    #            - After=... 哪个时间之后可以调用 Before= ...

        - id: base
          uri: lb://BASE-SERVER	 # lb(loadBalanced) 负载均衡
          predicates: # 断言 数组多个条件满足才转发
            - Path=/base-api  # 作为匹配规则在全局过滤中去掉

        - id: card
          uri: lb://CARD-SERVER
          predicates:
            - Path=/card-api
#
      default-filters: # 全局过滤
        - StripPrefix=1 # 去掉请求前缀1个 解决前后端分离的url前缀问题 例如前端请求地址http://xx/hello/world 过滤后为http://xx/world






