wayne:
  host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${wayne.host}:8761/eureka

spring:
  # 默认数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # 连接池类型
    url: jdbc:mysql://${wayne.host}:3306/card?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 #空闲时最小连接数
      maximum-pool-size: 20 #连接池大小
      data-source-properties:
        cachePrepStmts: true #是否启用Prep缓存
        prepStmtCacheSize: 250 #Prep缓存大小
        prepStmtCacheSqlLimit: 2048 #Prep缓存sql限制大小
        useServerPrepStmts: true #是否用服务缓存Prep
  # spring cache
  cache:
    cache-names: c1,diff
  # redis
  redis:
    timeout: 60000ms   # 连接超时时间（毫秒）
    database: 0        # 数据库索引（默认为0）
    password:          # 密码，若没有，不填写
    cluster:
      nodes: ${wayne.host}:6379,${wayne.host}:6379
#        - ${wayne.host}:6379
#        - 127.0.0.1:7032
      max-redirects: 3
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5      # 连接池中的最大空闲连接
        min-idle: 2      # 连接池中的最小空闲连接
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

# Hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true          # Hystrix是否启用超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 20000 # Hystrix断路器的超时时间，默认是1s，断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试




