wayne:
  host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${wayne.host}:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource # 连接池类型
    url: jdbc:mysql://${wayne.host}:3306/card?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5 #空闲时最小连接数
      maximum-pool-size: 20 #连接池大小
      data-source-properties:
        cachePrepStmts: true #是否启用Prep缓存
        prepStmtCacheSize: 250 #Prep缓存大小
        prepStmtCacheSqlLimit: 2048 #Prep缓存sql限制大小
        useServerPrepStmts: true #是否用服务缓存Prep
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    org.wayne.thief.mapper: debug
# Feign调用配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
# ribbon配置
ribbon:
  ConnectTimeout: 10000       # ribbon请求连接的超时时间（ms）
  ReadTimeout: 10000        # 请求处理的超时时间（ms）
  OkToRetryOnAllOperations: true  # 是否对所有请求操作都进行重试
  MaxAutoRetries: 0         # 当前服务404不重试
  MaxAutoRetriesNextServer: 1   # 404切换一次服务实例
  serverListRefreshInterval: 2000 # 刷新服务列表时间间隔（ms）
  eureka:
    enabled: true         # 是否启用eureka列表拉取

# Hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true          # Hystrix是否启用超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 20000 # Hystrix断路器的超时时间，默认是1s，断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试
