server:
  port: 8761

spring:
  application:
    name: eureka-a

eureka:
  instance:
    hostname: eureka-a
  client:
    # 都为true互相注册
    registerWithEureka:  true
    fetchRegistry: true
    # 注册到eureka-b上
    serviceUrl:
      defaultZone: http://eureka-b:8762/eureka
