package org.wayne.entity;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DeductApply generated by hbm2java
 */
@Entity
@Table(name = "deduct_apply")
public class DeductApply implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /** 
    * 扣款申请序号.
    */
    private Long deductApplySeq;
    /** 
    * 资产方.
    */
    private String assetSide;
    /** 
    * 资金方.
    */
    private String capitalSide;
    /** 
    * 扣款申请号/交易流水号.
    */
    private String deductApplyNo;
    /** 
    * 订单号.
    */
    private String applyNo;
    /** 
    * 申请人姓名.
    */
    private String name;
    /** 
    * 身份证号.
    */
    private String certCode;
    /** 
    * 借据编号.
    */
    private String creditNum;
    /** 
    * 产品编码 .
    */
    private String prdCode;
    /** 
    * 申请日期/客户预约日期.
    */
    private String deductApplyDate;
    /** 
    * 扣款营业日期.
    */
    private String openDay;
    /** 
    * 应扣款金额.
    */
    private BigDecimal deductAmt;
    /** 
    * 应扣款本金.
    */
    private BigDecimal deductPrincipal;
    /** 
    * 应扣款利息.
    */
    private BigDecimal deductNor;
    /** 
    * 应扣款罚息.
    */
    private BigDecimal deductOver;
    /** 
    * 应扣款复利.
    */
    private BigDecimal deductCom;
    /** 
    * 平账日期.
    */
    private String feeDate;
    /** 
    * 还款类型/结算类型 00-期次提前还款,01-期次正常还款,02-提前结清 ,09-提前代偿,03-期次代偿,04-全额代偿.
    */
    private String refundMethod;
    /** 
    * 期数.
    */
    private Integer termNum;
    /** 
    * 状态 00-成功,10-申请指令,01-处理中,02-核心扣款中,03-核心扣款成功, 99-失败.
    */
    private String status;
    /** 
    * 执行步骤.
    */
    private String step;
    /** 
    * 投递mq次数.
    */
    private Integer sendMqNum;
    /** 
    * MQ执行标识.
    */
    private String deductFlag;
    /** 
    * 还款账户.
    */
    private String refundAcct;
    /** 
    * 核心记账日期.
    */
    private String bankOpenDay;
    /** 
    * 扣款信息.
    */
    private String message;
    /** 
    * 是否入账 Y-是，N-否.
    */
    private String ifRecordBill;
    /** 
    * 开始落库时间.
    */
    private String startModifyTime;
    /** 
    * 最后修改时间.
    */
    private Date lastModifyTime;
    /** 
    * 发送银行流水号.
    */
    private String flowNo;
    /** 
    * 银行流水号.
    */
    private String bankFlowNo;
    /** 
    * 监控时间.
    */
    private Date MTime;

    public DeductApply() {
    }

    public DeductApply(String assetSide, String capitalSide) {
        this.assetSide = assetSide;
        this.capitalSide = capitalSide;
    }

    public DeductApply(String assetSide, String capitalSide, String deductApplyNo, String applyNo, String name,
                       String certCode, String creditNum, String prdCode, String deductApplyDate, String openDay,
                       BigDecimal deductAmt, BigDecimal deductPrincipal, BigDecimal deductNor, BigDecimal deductOver,
                       BigDecimal deductCom, String feeDate, String refundMethod, Integer termNum, String status, String step,
                       Integer sendMqNum, String deductFlag, String refundAcct, String bankOpenDay, String message,
                       String ifRecordBill, String startModifyTime, Date lastModifyTime, String flowNo, String bankFlowNo,
                       Date MTime) {
        this.assetSide = assetSide;
        this.capitalSide = capitalSide;
        this.deductApplyNo = deductApplyNo;
        this.applyNo = applyNo;
        this.name = name;
        this.certCode = certCode;
        this.creditNum = creditNum;
        this.prdCode = prdCode;
        this.deductApplyDate = deductApplyDate;
        this.openDay = openDay;
        this.deductAmt = deductAmt;
        this.deductPrincipal = deductPrincipal;
        this.deductNor = deductNor;
        this.deductOver = deductOver;
        this.deductCom = deductCom;
        this.feeDate = feeDate;
        this.refundMethod = refundMethod;
        this.termNum = termNum;
        this.status = status;
        this.step = step;
        this.sendMqNum = sendMqNum;
        this.deductFlag = deductFlag;
        this.refundAcct = refundAcct;
        this.bankOpenDay = bankOpenDay;
        this.message = message;
        this.ifRecordBill = ifRecordBill;
        this.startModifyTime = startModifyTime;
        this.lastModifyTime = lastModifyTime;
        this.flowNo = flowNo;
        this.bankFlowNo = bankFlowNo;
        this.MTime = MTime;
    }

    /** 
     * 扣款申请序号.
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "deduct_apply_seq", unique = true, nullable = false)
    public Long getDeductApplySeq() {
        return this.deductApplySeq;
    }

    /** 
     * 扣款申请序号.
     */
    public void setDeductApplySeq(Long deductApplySeq) {
        this.deductApplySeq = deductApplySeq;
    }

    /** 
     * 资产方.
     */
    @Column(name = "asset_side", nullable = false, length = 10)
    public String getAssetSide() {
        return this.assetSide;
    }

    /** 
     * 资产方.
     */
    public void setAssetSide(String assetSide) {
        this.assetSide = assetSide;
    }

    /** 
     * 资金方.
     */
    @Column(name = "capital_side", nullable = false, length = 10)
    public String getCapitalSide() {
        return this.capitalSide;
    }

    /** 
     * 资金方.
     */
    public void setCapitalSide(String capitalSide) {
        this.capitalSide = capitalSide;
    }

    /** 
     * 扣款申请号/交易流水号.
     */
    @Column(name = "deduct_apply_no", length = 100)
    public String getDeductApplyNo() {
        return this.deductApplyNo;
    }

    /** 
     * 扣款申请号/交易流水号.
     */
    public void setDeductApplyNo(String deductApplyNo) {
        this.deductApplyNo = deductApplyNo;
    }

    /** 
     * 订单号.
     */
    @Column(name = "apply_no", length = 50)
    public String getApplyNo() {
        return this.applyNo;
    }

    /** 
     * 订单号.
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    /** 
     * 申请人姓名.
     */
    @Column(name = "name", length = 50)
    public String getName() {
        return this.name;
    }

    /** 
     * 申请人姓名.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** 
     * 身份证号.
     */
    @Column(name = "cert_code", length = 30)
    public String getCertCode() {
        return this.certCode;
    }

    /** 
     * 身份证号.
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode;
    }

    /** 
     * 借据编号.
     */
    @Column(name = "credit_num", length = 50)
    public String getCreditNum() {
        return this.creditNum;
    }

    /** 
     * 借据编号.
     */
    public void setCreditNum(String creditNum) {
        this.creditNum = creditNum;
    }

    /** 
     * 产品编码 .
     */
    @Column(name = "prd_code", length = 30)
    public String getPrdCode() {
        return this.prdCode;
    }

    /** 
     * 产品编码 .
     */
    public void setPrdCode(String prdCode) {
        this.prdCode = prdCode;
    }

    /** 
     * 申请日期/客户预约日期.
     */
    @Column(name = "deduct_apply_date", length = 20)
    public String getDeductApplyDate() {
        return this.deductApplyDate;
    }

    /** 
     * 申请日期/客户预约日期.
     */
    public void setDeductApplyDate(String deductApplyDate) {
        this.deductApplyDate = deductApplyDate;
    }

    /** 
     * 扣款营业日期.
     */
    @Column(name = "open_day", length = 20)
    public String getOpenDay() {
        return this.openDay;
    }

    /** 
     * 扣款营业日期.
     */
    public void setOpenDay(String openDay) {
        this.openDay = openDay;
    }

    /** 
     * 应扣款金额.
     */
    @Column(name = "deduct_amt")
    public BigDecimal getDeductAmt() {
        return this.deductAmt;
    }

    /** 
     * 应扣款金额.
     */
    public void setDeductAmt(BigDecimal deductAmt) {
        this.deductAmt = deductAmt;
    }

    /** 
     * 应扣款本金.
     */
    @Column(name = "deduct_principal")
    public BigDecimal getDeductPrincipal() {
        return this.deductPrincipal;
    }

    /** 
     * 应扣款本金.
     */
    public void setDeductPrincipal(BigDecimal deductPrincipal) {
        this.deductPrincipal = deductPrincipal;
    }

    /** 
     * 应扣款利息.
     */
    @Column(name = "deduct_nor")
    public BigDecimal getDeductNor() {
        return this.deductNor;
    }

    /** 
     * 应扣款利息.
     */
    public void setDeductNor(BigDecimal deductNor) {
        this.deductNor = deductNor;
    }

    /** 
     * 应扣款罚息.
     */
    @Column(name = "deduct_over")
    public BigDecimal getDeductOver() {
        return this.deductOver;
    }

    /** 
     * 应扣款罚息.
     */
    public void setDeductOver(BigDecimal deductOver) {
        this.deductOver = deductOver;
    }

    /** 
     * 应扣款复利.
     */
    @Column(name = "deduct_com")
    public BigDecimal getDeductCom() {
        return this.deductCom;
    }

    /** 
     * 应扣款复利.
     */
    public void setDeductCom(BigDecimal deductCom) {
        this.deductCom = deductCom;
    }

    /** 
     * 平账日期.
     */
    @Column(name = "fee_date", length = 20)
    public String getFeeDate() {
        return this.feeDate;
    }

    /** 
     * 平账日期.
     */
    public void setFeeDate(String feeDate) {
        this.feeDate = feeDate;
    }

    /** 
     * 还款类型/结算类型 00-期次提前还款,01-期次正常还款,02-提前结清 ,09-提前代偿,03-期次代偿,04-全额代偿.
     */
    @Column(name = "refund_method", length = 20)
    public String getRefundMethod() {
        return this.refundMethod;
    }

    /** 
     * 还款类型/结算类型 00-期次提前还款,01-期次正常还款,02-提前结清 ,09-提前代偿,03-期次代偿,04-全额代偿.
     */
    public void setRefundMethod(String refundMethod) {
        this.refundMethod = refundMethod;
    }

    /** 
     * 期数.
     */
    @Column(name = "term_num")
    public Integer getTermNum() {
        return this.termNum;
    }

    /** 
     * 期数.
     */
    public void setTermNum(Integer termNum) {
        this.termNum = termNum;
    }

    /** 
     * 状态 00-成功,10-申请指令,01-处理中,02-核心扣款中,03-核心扣款成功, 99-失败.
     */
    @Column(name = "status", length = 3)
    public String getStatus() {
        return this.status;
    }

    /** 
     * 状态 00-成功,10-申请指令,01-处理中,02-核心扣款中,03-核心扣款成功, 99-失败.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** 
     * 执行步骤.
     */
    @Column(name = "step", length = 2)
    public String getStep() {
        return this.step;
    }

    /** 
     * 执行步骤.
     */
    public void setStep(String step) {
        this.step = step;
    }

    /** 
     * 投递mq次数.
     */
    @Column(name = "send_mq_num")
    public Integer getSendMqNum() {
        return this.sendMqNum;
    }

    /** 
     * 投递mq次数.
     */
    public void setSendMqNum(Integer sendMqNum) {
        this.sendMqNum = sendMqNum;
    }

    /** 
     * MQ执行标识.
     */
    @Column(name = "deduct_flag", length = 10)
    public String getDeductFlag() {
        return this.deductFlag;
    }

    /** 
     * MQ执行标识.
     */
    public void setDeductFlag(String deductFlag) {
        this.deductFlag = deductFlag;
    }

    /** 
     * 还款账户.
     */
    @Column(name = "refund_acct", length = 50)
    public String getRefundAcct() {
        return this.refundAcct;
    }

    /** 
     * 还款账户.
     */
    public void setRefundAcct(String refundAcct) {
        this.refundAcct = refundAcct;
    }

    /** 
     * 核心记账日期.
     */
    @Column(name = "bank_open_day", length = 20)
    public String getBankOpenDay() {
        return this.bankOpenDay;
    }

    /** 
     * 核心记账日期.
     */
    public void setBankOpenDay(String bankOpenDay) {
        this.bankOpenDay = bankOpenDay;
    }

    /** 
     * 扣款信息.
     */
    @Column(name = "message", length = 500)
    public String getMessage() {
        return this.message;
    }

    /** 
     * 扣款信息.
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /** 
     * 是否入账 Y-是，N-否.
     */
    @Column(name = "if_record_bill", length = 1)
    public String getIfRecordBill() {
        return this.ifRecordBill;
    }

    /** 
     * 是否入账 Y-是，N-否.
     */
    public void setIfRecordBill(String ifRecordBill) {
        this.ifRecordBill = ifRecordBill;
    }

    /** 
     * 开始落库时间.
     */
    @Column(name = "start_modify_time", length = 32)
    public String getStartModifyTime() {
        return this.startModifyTime;
    }

    /** 
     * 开始落库时间.
     */
    public void setStartModifyTime(String startModifyTime) {
        this.startModifyTime = startModifyTime;
    }

    /** 
     * 最后修改时间.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_modify_time", length = 19)
    public Date getLastModifyTime() {
        return this.lastModifyTime;
    }

    /** 
     * 最后修改时间.
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /** 
     * 发送银行流水号.
     */
    @Column(name = "flow_no", length = 40)
    public String getFlowNo() {
        return this.flowNo;
    }

    /** 
     * 发送银行流水号.
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo;
    }

    /** 
     * 银行流水号.
     */
    @Column(name = "bank_flow_no", length = 40)
    public String getBankFlowNo() {
        return this.bankFlowNo;
    }

    /** 
     * 银行流水号.
     */
    public void setBankFlowNo(String bankFlowNo) {
        this.bankFlowNo = bankFlowNo;
    }

    /** 
     * 监控时间.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "m_time", length = 19)
    public Date getMTime() {
        return this.MTime;
    }

    /** 
     * 监控时间.
     */
    public void setMTime(Date MTime) {
        this.MTime = MTime;
    }

}
